"""Initial schema

Revision ID: 6dc91e421020
Revises: 
Create Date: 2026-02-08 23:05:38.958605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc91e421020'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('google_refresh_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('calendar_sync_state',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_calendar_id', sa.String(), nullable=True),
    sa.Column('sync_token', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('webhook_channel_id', sa.String(), nullable=True),
    sa.Column('webhook_resource_id', sa.String(), nullable=True),
    sa.Column('webhook_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('fixed_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('google_start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('google_end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_google_event', sa.Boolean(), nullable=True),
    sa.Column('google_event_id', sa.String(), nullable=True),
    sa.Column('last_updated_source', sa.String(length=10), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.CheckConstraint("last_updated_source IN ('APP', 'GOOGLE')"),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixed_slots')
    op.drop_table('calendar_sync_state')
    op.drop_table('users')
    # ### end Alembic commands ###
